version: '3.9'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      # - elasticsearch.username=root
      - elasticsearch.password=1234
      - ELASTICSEARCH_USERNAME=root
      # - ELASTIC_PASSWORD=1234
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=true #false disable security (dev only)
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/es01/es01.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.enabled=true 
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/es01/es01.key
      # - xpack.security.http.ssl.enabled=false  # Elasticsearch 7.x you can keep HTTP without TLS first/
      - ES_JAVA_OPTS=-Xms512m -Xmx512m   # limit ES to 512m heap
    ulimits:
      memlock: #disable swap for performance
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR
    ports:
      - "9200:9200" # API
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - NODE_OPTIONS=--max-old-space-size=512   # limit Kibana to 512MB
      - xpack.encryptedSavedObjects.encryptionKey=true
    ports:
      - "5601:5601" # dashboard
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  es_data:

networks:
  elk:
